import { Metadata } from "next";

export const metadata: Metadata = {
  title: "StreetGrub | Home",
  description: "Generated by streetGrub Home page",
};
const Dashbaord = async () => {
  return <div></div>;
};

export default Dashbaord;
